{{- if .Values.imagePullSecrets.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "codethreat.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"registry.codethreat.com\":{\"username\":\"license\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.imagePullSecrets.token (printf "license:%s" .Values.imagePullSecrets.token | b64enc) | b64enc }}
{{- end }}
