{{- if and .Values.appsec.enabled (ne .Values.appsec.uploads.storage.storageClass "-") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codethreat.fullname" . }}-appsec-uploads
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "codethreat.componentLabels" (dict "component" "appsec" "context" .) | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.appsec.uploads.storage.size }}
  {{- if .Values.appsec.uploads.storage.storageClass }}
  storageClassName: {{ .Values.appsec.uploads.storage.storageClass }}
  {{- end }}
{{- end }}
